### PR TITLE
benchmark-data is not in benchutils directory

### PR DESCRIPTION
**Pull request by MHBauer**
It is located one directory up in the root of the project.

mine output is not in color either.

### CODE REVIEW

**Review by whereswaldon — CHANGES_REQUESTED** [review]
Thank you! Do you mind doing `git commit -s --amend && git push -f` to Sign Off that you agree to the [DCO](https://github.com/hyperledger/fabric/blob/master/docs/source/DCO1.1.txt)?

**Comment by MHBauer** [comment]
ya, not a problem. Should probably enable the dco bot on the repo if possible. Help automate that check.

**Comment by MHBauer** [comment]
100000-elements

my pretty graph :-D

**Review by whereswaldon — APPROVED** [review]

**Comment by whereswaldon** [comment]
I've opened #3 to track the color problem. Thank you!

**Pull request merged**
